# Configuración de colores Ayu Dark
colors:
  # Colores predeterminados
  primary:
    background: '#0A0E14'
    foreground: '#B3B1AD'

  # Colores normales
  normal:
    black:   '#01060E'
    red:     '#EA6C73'
    green:   '#91B362'
    yellow:  '#F9AF4F'
    blue:    '#53BDFA'
    magenta: '#FFB454'
    cyan:    '#95E6CB'
    white:   '#C7C7C7'

  # Colores brillantes
  bright:
    black:   '#686868'
    red:     '#F07178'
    green:   '#C2D94C'
    yellow:  '#FFB454'
    blue:    '#59C2FF'
    magenta: '#FFEE99'
    cyan:    '#95E6CB'
    white:   '#FFFFFF'
