#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Windows 10"  --class windows --class os {
	
	search --fs-uuid --no-floppy --set=root 5DDE-A9E7
	drivemap -s (hd0) ${root}
	chainloader (${root})/EFI/Microsoft/Boot/bootmgfw.efi
}
menuentry "Windows"{
	set root=(hd0,1)
	chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}
