#! /bin/sh

# Redirigir errores a un archivo log
exec 2>>"$HOME/.bspwm_errors.log"

# ----- IMPORT ----- #

# Cargar configuraciones adicionales (si existen)
[ -f "$HOME/.config/bspwm/modules/rules.conf" ] && . "$HOME/.config/bspwm/modules/rules.conf"
[ -f "$HOME/.config/bspwm/modules/init.conf" ] && . "$HOME/.config/bspwm/modules/init.conf"

# ----- CORRECCIÓN PARA APLICACIONES JAVA ----- #
export _JAVA_AWT_WM_NONREPARENTING=1

# ----- RECURSOS ----- #
export QT_QPA_PLATFORMTHEME=qt5ct

# ----- CONFIGURACIÓN DE MONITORES Y ESCRITORIOS ----- #
xrandr -q | grep -w 'connected' | cut -d' ' -f1 | xargs -I{} bspc monitor {} -d '1' '2' '3' '4' '5' '6'


# ----- CONFIGURACIÓN GENERAL ----- #
xsetroot -cursor_name left_ptr

# Configuración de colores y bordes de ventanas
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 0
bspc config borderless_monocle false
bspc config top_padding 36


# Colores adicionales
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# Comportamiento del ratón
bspc config focus_follows_pointer true
bspc config split_ratio 0.52

# ----- CONFIGURACIÓN DE GAPS ----- #
bspc config gapless_monocle false
bspc config window_gap 6

# ----- CONFIGURACIÓN DE RATÓN Y MOVER/REDIMENSIONAR VENTANAS ----- #
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


xautolock -time 10 -locker '/bin/lockscreen' &
