#!/usr/bin/env bash

# Directorio donde se encuentran los iconos
DIR="$HOME/.config/bspwm/assets"
# Número de pasos de brillo
BRIGHTNESS_STEPS=5

# Función para obtener el brillo actual
function get_brightness {
  brightnessctl i | grep -oP '\(\K[^%\)]+'
}

# Función para enviar notificaciones
function send_notification {
  local icon="$DIR/brightness.svg"
  local brightness=$(get_brightness)
  local bar=$(seq -s "─" 0 $((brightness / 5)) | sed 's/[0-9]//g')
  # Enviar la notificación con la barra de brillo
  dunstify -a Brightness "$brightness%" "$(echo -e "[$bar]")" -i "$icon" -r 5555 -u normal -h int:value:$(($brightness))
}

# Verificar si se proporcionó un argumento
if [[ $# -ne 1 ]]; then
  echo "Uso: $0 [up|down]"
  exit 1
fi

# Manejar los argumentos
case $1 in
  up)
    # Aumentar el brillo en un 5%
    brightnessctl set "${BRIGHTNESS_STEPS:-5}%+" -q
    send_notification
    ;;
  down)
    # Disminuir el brillo en un 5%
    brightnessctl set "${BRIGHTNESS_STEPS:-5}%-" -q
    send_notification
    ;;
esac
