#!/bin/bash

# Ruta de la carpeta de imágenes
WALLPAPER_DIR="$HOME/Wallpapers"

# Lista de imágenes en la carpeta
IMAGES=("$WALLPAPER_DIR"/*)

# Selecciona una imagen aleatoria
RANDOM_IMAGE="${IMAGES[RANDOM % ${#IMAGES[@]}]}"

# Configura el fondo de pantalla
feh --bg-scale "$RANDOM_IMAGE"
