#!/bin/bash


function get_volume {
  pactl list sinks | grep -A 15 '^[[:space:]]Volume:' | grep -Po '[0-9]+%' | head -1 | grep -oP '[0-9]+'
}
  volumen=$(get_volume)
  status_volumen="$(pactl list sinks | awk '/Mute:/ {print $2}')"
  if [ "$status_volumen" = "yes" ]; then
    echo "$DIR/mute.svg"
  elif [ "$volumen" -eq 0 ]; then
    echo "$DIR/mute.svg"
  elif [ "$volumen" -lt 30 ]; then
    echo "$DIR/low_volume.svg"
  elif [ "$volumen" -lt 70 ]; then
    echo "$DIR/medium_volume.svg"
  else
    echo "$DIR/high_volume.svg"
  fi
